//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Configuracione
    {
        public int Id { get; set; }
        public Nullable<decimal> Couta_Fija { get; set; }
        public Nullable<decimal> Mora { get; set; }
        public Nullable<decimal> Valor_Metro { get; set; }
        public Nullable<decimal> Valor_Metro2 { get; set; }
        public Nullable<decimal> Valor_Metro3 { get; set; }
        public Nullable<decimal> Multa { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> Estado { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
