//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Cargo { get; set; }
        public string DUI { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Dirrecion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fechar_Registro { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
