//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripcione()
        {
            this.PagoInscripcions = new HashSet<PagoInscripcion>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<decimal> Monto_Pagar { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Estado_Config { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<int> Estado2 { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoInscripcion> PagoInscripcions { get; set; }
    }
}
