//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lectura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lectura()
        {
            this.Pagos = new HashSet<Pago>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Lectura1 { get; set; }
        public string Estado_Lectura { get; set; }
        public Nullable<int> Estado { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> ClientesId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagos { get; set; }
    }
}
