//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoInscripcion
    {
        public int Id { get; set; }
        public Nullable<int> InscripcionId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Inscripcione Inscripcione { get; set; }
    }
}
