//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemWalter.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.MoraClientes = new HashSet<MoraCliente>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Lectura_Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> Numero_Factura { get; set; }
        public Nullable<int> Lectura_Anterior { get; set; }
        public Nullable<int> Lectura_Actual { get; set; }
        public Nullable<int> Consumo { get; set; }
        public Nullable<decimal> Cuota_Fija { get; set; }
        public Nullable<decimal> Mes_Atrasado { get; set; }
        public Nullable<decimal> Mora { get; set; }
        public Nullable<decimal> Total { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Lectura { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Pago { get; set; }     
        public Nullable<int> Estado { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Lectura Lectura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoraCliente> MoraClientes { get; set; }
    }
}
